### ISSUE TITLE
Unrelated tabs (not blank) aren't detected as unrelated under unknown conditions, breaking an option

### ISSUE THREAD

**Issue by ghost** [zeird/tabcontrol#13]
Firefox 39.0
Tab Control 0.7.8.1
'Insert related tabs after current' - checked (and works fine)
'In a left-to-right group' - checked (and works fine)
'Insert unrelated tabs after current as well' - checked but new unrelated tabs STILL open at the end of the tab bar.
Any ideas?
Thanks.

**Comment by lebedev** [comment]
For a start, does this option really toggle? I mean, for example, if it was checked and then you uncheck it and press OK, then open the add-on's options again - it should stay unchecked. Some users have a bug with inability to toggle the add-on's options (I don't know what causes this yet, worksforme).
Then I want you to check the browser console. I want you to follow [2-4 steps from here](https://github.com/zeird/tabcontrol/issues/10#issuecomment-126457342), then open unrelated tab (a blank tab or a tab from library/history/bookmarks) and then tell me if there's any errors in the browser console.

**Comment by lebedev** [comment]
Also, Tab Control add-on might be in a conflict with some other add-on. Try to disable all other add-ons and check if the bug is gone.

**Comment by ghost** [comment]
'For a start, does this option really toggle?' - yes, absolutely sure it's enabled.
'Try to disable all other add-ons and check if the bug is gone.' - disabled everything except Tab Control and the issue still persists.
Will try to check the browser console now...

**Comment by ghost** [comment]
BTW, if I just open a new tab (Ctrl+T), it does open next to the active tab. But NOT new unrelated tabs from, e.g. the Bookmarks Toolbar...

**Comment by ghost** [comment]
'then tell me if there's any errors in the browser console.' - there's lots of text which doesn't make any sense to me. For example:

(a lot of apparently not useful info omitted)

**Comment by lebedev** [comment]
> 'For a start, does this option really toggle?' - yes, absolutely sure it's enabled.

That's not it. Can you disable it? Will it stay unchecked?

> BTW, if I just open a new tab (Ctrl+T), it does open next to the active tab. But NOT new unrelated tabs from, e.g. the Bookmarks Toolbar...
> 
> there's lots of text which doesn't make any sense to me. For example:

Ok. Now we know that Tab Control doesn't throw any errors.

It's kinda hard for me to resolve this bug because it worksforme and I don't know special conditions why it doesn't work for you yet.

Next step: let's check if this is because of some Firefox's preferences. Please create a new clean profile (with `firefox -p --no-remote` command), then install Tab Control only and verify that the bug persists.

**Comment by ghost** [comment]
'Can you disable it? Will it stay unchecked?' - yes, it does stay unchecked if I disable it.
'let's check if this is because of some Firefox's preferences' - got to go now but I'll try it tomorrow.
Thanks.

**Comment by ghost** [comment]
'Next step: let's check if this is because of some Firefox's preferences. Please create a new clean profile (with firefox -p --no-remote command), then install Tab Control only and verify that the bug persists.' - no problem with a new profile!! So it's some kind of conflict with the Firefox preferences, right? Any way to resolve it without having to create a new profile?

**Comment by lebedev** [comment]
> So it's some kind of conflict with the Firefox preferences, right?

Seems like it.

> Any way to resolve it without having to create a new profile?

Let's find out:
1. Open your regular profile folder. To do this, open blank tab, enter `about:support`, and then click `Show folder` button near `Profile Folder`.
![](http://i.imgur.com/BD3DdmH.png)
2. You'll find `prefs.js` file there. Close Firefox, rename `prefs.js` to, for example, `prefs.js_old`, start Firefox. Verify that the problem is gone. 
3. Close Firefox again, delete new `prefs.js` that Firefox would create and rename `prefs.js_old` back to `prefs.js`, start Firefox.
4. If the problem is gone in p. 2, I want you to send me the contents of your `prefs.js` and I'll check it for conflicting options. Make sure that it doesn't contain any personal/confidential data (such as passwords and/or logins, replace all the info you don't want to share with asterisks or just delete it, for example).

**Comment by ghost** [comment]
'2. You'll find prefs.js file there. Close Firefox, rename prefs.js to, for example, prefs.js_old, start Firefox. Verify that the problem is gone.' - unfortunately, the problem still persists: new unrelated tabs continue to open at the end of the tab bar :(

Is it possible that something is wrong with my version of Firefox rather than the add-on?

**Comment by lebedev** [comment]
Let's summarize what we know about your issue:
- The bug persists when you disable all other add-ons.
- The bug persists after you reset all Firefox preferences (by renaming `prefs.js` in your Firefox profile folder when Firefox is closed).
- There's no problem with a clean profile.

> Is it possible that something is wrong with my version of Firefox rather than the add-on?

Unlikely. I suppose it's something wrong with your profile, not the Firefox application itself.

If you don't have many highly customized add-ons I suggest you to backup your profile folder and then try to reset your profile (that will likely solve your problem):
1. Type `about:support` in your address bar, press `Refresh Firefox...` (on the right side of the page), follow instructions that Firefox will show you.
![](http://i.imgur.com/Guacrmr.png)
2. If there's no `Refresh Firefox...` button, press `Restart with Add-ons Disabled...` button instead, and then press `Refresh Firefox` in the following modal window and follow instructions.
![](http://i.imgur.com/QFbWmWr.png)
3. Then reinstall all add-ons and set all the options you need.

If that fails, then, unfortunately, I'm out of ideas. Creating a clean profile is the last option.

_EDIT_: it's `about:support` in the first step.

**Comment by ghost** [comment]
I think you're right - it's probably my profile causing the problem. Unfortunately, I do have quite a lot of add-ons (about 30) and it would be quite a hassle refreshing Firefox now, although it's likely the best option. Anyway, since it's apparently not an issue with the add-on itself, I'll edit my review at addons.mozilla.org and give Tab Control a five-star rating. Keep up the good work and thanks for the help!

**Comment by lebedev** [comment]
I'm sorry that I can't solve your problem. As a workaround you may install [other add-on for this functionality](https://addons.mozilla.org/addon/open-tabs-next-to-current/) with or without Tab Control. That add-on would likely break `In a left-to-right group` behavior though.
