### ISSUE TITLE
Compatibility with Tab Groups add-on

### ISSUE THREAD

**Issue by Quicksaver** [zeird/tabcontrol#14]
See https://github.com/Quicksaver/Tab-Groups/issues/85 for a description of the bug.

I've already fixed it within Tab Groups, but I'm letting you know about this anyway in case you'd like to integrate it in Tab Control. Basically gTabControl.onTabClose should no-op if closing a tab while in groups mode: https://github.com/Quicksaver/Tab-Groups/commit/91d180846ab65d4f008f035979dbb2a48c48fd8b

**Comment by lebedev** [comment]
I'll look into it, thanks.

**Comment by lebedev** [comment]
@Quicksaver, is and will be `window.TabView.isVisible()` a relying method to detect if groups mode is active?

**Comment by Quicksaver** [comment]
At least as far as my add-on is concerned yeah. With the add-on enabled, `window` will always have a `TabView` property and its `isVisible()`.

**Comment by lebedev** [comment]
Now we wait until version `0.7.8.2` is reviewed on AMO, so I guess your fix in `tabgroups@quicksaver` would be an overkill.
