### ISSUE TITLE
"Position new tabs to right of current tab" option can be improved

### ISSUE THREAD

**Issue by lebedev** [zeird/tabcontrol#6]
It is possible to use `about:config` preference `browser.tabs.insertRelatedAfterCurrent` instead of custom one for this option. However, `browser.tabs.insertRelatedAfterCurrent` doesn't affect new tab position: it opens at the end of the tabs bar. So maybe there should be another option "Open blank tabs after current"? Like this:
- [x] `Insert related tabs after current tab` (enabled by default)
  - [x] `In a left-to-right group` (enabled by default)
  - [x] `Open blank tabs after current as well` (enabled by default)

And that new option should be localized somehow.

**Comment by jesus2099** [comment]
It would be nice, like in Opera.

**Comment by lebedev** [comment]
I discovered how Firefox decides where to put a tab (if `browser.tabs.insertRelatedAfterCurrent` is `true`) - if a tab has `owner` property (meaning that tab was opened from another tab), Firefox puts it after current, if not (blank tabs of tabs opened from history/bookmarks) - it places it at the end of tabs bar.

**EDIT**: it's vice versa with `owner` property actually.
