### ISSUE TITLE
'Focus left tab when closing current tab' doesn't work when left tab is pinned

### ISSUE THREAD

**Issue by Torvin** [zeird/tabcontrol#7]
In 2da295f you've introduced a new 'feature' - when left tab is pinned, it doesn't get activated. I want an option to get the previous behaviour back!
I usually have the RSS client (pinned), click on a link in an RSS entry - that opens in a new tab - read it, close it, and bam! - now I don't get back to my RSS client anymore.

**Comment by lebedev** [comment]
> a new 'feature' - when left tab is pinned, it doesn't get activated.

It does (when there're no other non-pinned tabs left). But you're right — current behavior doesn't exactly follow the option name. Will fix.

**Comment by lebedev** [comment]
It should work as expected now (in 0.7.8).

**Comment by Torvin** [comment]
Yay! Thank you.
